services:
  backend:
    build: ./backend
    expose:
      - "8000"
    working_dir: /app
    volumes:
      - ./backend:/app:rw
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16.1
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
