services:
  db:
    image: postgres:16.1
    env_file: ./.env
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"   # em produção, evite expor

  backend:
    build: ./backend
    env_file: ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db:
