"""create properties table

Revision ID: 11a733596756
Revises: b51f944dd4fb
Create Date: 2025-08-23 00:24:56.696812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a733596756'
down_revision: Union[str, Sequence[str], None] = 'b51f944dd4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('property_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_reservations_property_id'), 'reservations', ['property_id'], unique=False)
    op.create_foreign_key(None, 'reservations', 'properties', ['property_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_index(op.f('ix_reservations_property_id'), table_name='reservations')
    op.drop_column('reservations', 'property_id')
    # ### end Alembic commands ###
