"""add is_active to reservations and FK props

Revision ID: 1bcc59a95f24
Revises: 11a733596756
Create Date: 2025-08-24 16:25:10.546718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcc59a95f24'
down_revision: Union[str, Sequence[str], None] = '11a733596756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'is_active')
    # ### end Alembic commands ###
