"""add is_active to reservations and FK props

Revision ID: 1e641b666d16
Revises: 8e4e23baebb3
Create Date: 2025-08-24 20:03:35.580892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e641b666d16'
down_revision: Union[str, Sequence[str], None] = '8e4e23baebb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'total_price')
    # ### end Alembic commands ###
