"""add is_active to reservations and FK props

Revision ID: 7f0e464aaf97
Revises: 1bcc59a95f24
Create Date: 2025-08-24 19:57:20.478359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0e464aaf97'
down_revision: Union[str, Sequence[str], None] = '1bcc59a95f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
