"""add is_active to reservations and FK props

Revision ID: 8e4e23baebb3
Revises: 7f0e464aaf97
Create Date: 2025-08-24 19:58:43.349105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e4e23baebb3'
down_revision: Union[str, Sequence[str], None] = '7f0e464aaf97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
