"""add is_active to reservations and FK props

Revision ID: ec6bfec9e1b3
Revises: 83e3051d4103
Create Date: 2025-08-24 20:27:55.300397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6bfec9e1b3'
down_revision: Union[str, Sequence[str], None] = '83e3051d4103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
